// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Z03pVFYLjAs7cxwi4Sr2jW-AHWpgR5k',
    appId: '1:475389689247:android:36c214e1e097f445eed1aa',
    messagingSenderId: '475389689247',
    projectId: 'noteclone-41a11',
    storageBucket: 'noteclone-41a11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVkazlflVMwScY9akOSbim3U_FFzxF3Ls',
    appId: '1:475389689247:ios:b0e209b2b837b1e8eed1aa',
    messagingSenderId: '475389689247',
    projectId: 'noteclone-41a11',
    storageBucket: 'noteclone-41a11.firebasestorage.app',
    iosBundleId: 'com.example.noteClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVkazlflVMwScY9akOSbim3U_FFzxF3Ls',
    appId: '1:475389689247:ios:b0e209b2b837b1e8eed1aa',
    messagingSenderId: '475389689247',
    projectId: 'noteclone-41a11',
    storageBucket: 'noteclone-41a11.firebasestorage.app',
    iosBundleId: 'com.example.noteClone',
  );
}
